
name: fcp-fdm-dal-stub-test

services:
  fcp-fdm-dal-stub:
    build:
      target: development
    command: npm test
    environment:
      AUTH_ENABLED: false
    volumes:
      - ./test:/home/node/test
      - ./coverage:/home/node/coverage
