type Message {
  correlationId: String!
  crn: BigInt
  sbi: Int
  recipient: String
  subject: String
  body: String
  status: String!
  created: String!
  lastUpdated: String!
  events: [Event!]
}

type Event {
  specversion: String!
  type: String!
  source: String!
  id: String!
  time: String!  
  subject: String
  datacontenttype: String  
  data: EventData
}

type EventData {
  correlationId: String!
  recipient: String!
  statusDetails: StatusDetails
  content: EventContent  
  crn: BigInt
  sbi: Int
  sourceSystem: String
  notifyTemplateId: String
  commsType: String
  personalisation: String
  reference: String
  oneClickUnsubscribeUrl: String
  emailReplyToId: String
}

type StatusDetails {
  status: String!
  errorCode: Int
  errors: [EventError!]
}

type EventError {
  error: String!
  message: String!
}

type EventContent {
  subject: String
  body: String
}

input MessageFilters {
  crn: BigInt
  sbi: Int
}
